[workspace]
members = [
    "bin/cli",
    "bin/client",
    "bin/node",
    "bin/runtime",
    "faucet/client",
    "faucet/pallet",
    "identity/cli",
    "identity/client",
    "identity/pallet",
    "identity/utils",
    "identity/ffi",
    "keystore",

]
