[workspace]
members = [
  "bin/cli",
  "bin/node",
  "client",
  "keystore",
  "pallet",
  "utils",
  "client-ffi",
  ]

[patch.crates-io]
substrate-subxt = { git = "https://github.com/dvc94ch/substrate-subxt", branch = "events-sub" }
