[package]
name = "test-client"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
client-faucet = { path = "../../faucet/client" }
client-identity = { path = "../../identity/client" }
substrate-subxt = "0.9.0"
utils-identity = { path = "../../identity/utils" }
