[package]
name = "cli-identity"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-std = { version = "=1.5.0", features = ["attributes"] }
exitfailure = "0.5.1"
clap = "3.0.0-beta.1"
client-identity = { path = "../../client" }
dirs = "2.0.2"
env_logger = "0.7.1"
ipfs-embed = "0.1.0"
sp-keyring = "2.0.0-rc2"
substrate-subxt = "0.8.0"
thiserror = "1.0.19"
utils-identity = { version = "0.1.0", path = "../../utils" }
